language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - rbx-2.1.1
  - rbx-2.1.5
  - rbx-2.2.0
  - rbx
  - jruby-19mode
  - jruby
  
matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx-2.1.1
    - rvm: rbx-2.1.5
    - rvm: rbx-2.2.0
    - rvm: rbx
    - rvm: jruby-19mode
    - rvm: jruby
    
before_install:
  - gem update --system
  - gem --version
  
script: bundle exec rspec
